### ISSUE TITLE
Cache lookup fails on key `__proto__`

### ISSUE THREAD

**Issue by max-schaefer** [isaacs/async-cache#29]
To reproduce:

```
node -e 'require("async-cache")({load:()=>{}}).get("__proto__",()=>{})'
```

fails with "TypeError: this._loading[key].push is not a function". ([RunKit](https://runkit.com/embed/ai9w1767p156))

I think this is due to the `get` method [directly using](https://github.com/isaacs/async-cache/blob/d8a0e9a2cd0332e380e9459591f18402828f975a/ac.js#L60) its `key` argument as a property name, which in this case messes up the prototype chain.

**Comment by isaacs** [comment]
This module is not maintained.  Please use [lru-cache](http://npm.im/lru-cache), which supports asynchronous caching in version 7.6 and higher.
