### ISSUE TITLE
When maxAge is 0, the cache never expires

### ISSUE THREAD

**Issue by kadishmal** [isaacs/async-cache#6]
In the development environment I don't want async-cache to cache the object, so I set `maxAge: 0`. In fact, this value is automatically set by the application based on which environment it has been launched at (*production* vs. *development*). 

However, for some reason when `maxAge: 0`, the cache never expires, and async-cache never updates the cache.

When I set `0` it should expire immediately.

**Comment by isaacs** [comment]
301 redirect: https://github.com/isaacs/node-lru-cache/issues/75
